name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: matthieuEv/File-Remover 
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze
      - name: Build
        run: python setup.py build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: build/exe.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: Voila la nouvelle version de FileRemover 🔥
          draft: false
          prerelease: false
  
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifact
  
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifact/windows-latest/*
            artifact/ubuntu-latest/*
          token: ${{ secrets.GITHUB_TOKEN }}
        
            